import { sqliteTable, text, integer, primaryKey, index } from 'drizzle-orm/sqlite-core';
export const scores=sqliteTable('quiz_scores',{visitor:text('visitor').notNull(),book:text('book').notNull(),score:integer('score').notNull(),updated:integer('updated').notNull()},t=>[primaryKey({columns:[t.visitor,t.book]})]);
export const profiles=sqliteTable('reader_profiles',{userId:text('user_id').primaryKey(),firstName:text('first_name').notNull(),lastName:text('last_name').notNull(),middleName:text('middle_name').notNull().default(''),nameKey:text('name_key').unique(),gender:text('gender').notNull(),role:text('role').notNull().default('student'),avatar:text('avatar').notNull(),created:integer('created').notNull(),updated:integer('updated').notNull()});
export const bonuses=sqliteTable('reader_bonuses',{userId:text('user_id').primaryKey(),points:integer('points').notNull(),updated:integer('updated').notNull()});
export const settings=sqliteTable('site_settings',{key:text('key').primaryKey(),value:text('value').notNull()});

export const visits=sqliteTable('site_visits',{visitor:text('visitor').notNull(),day:text('day').notNull(),userId:text('user_id'),views:integer('views').notNull(),lastSeen:integer('last_seen').notNull()},t=>[primaryKey({columns:[t.visitor,t.day]}),index('idx_site_visits_day').on(t.day),index('idx_site_visits_user').on(t.userId)]);
export const messages=sqliteTable('reader_messages',{id:text('id').primaryKey(),recipient:text('recipient').notNull(),body:text('body').notNull(),kind:text('kind').notNull().default('message'),created:integer('created').notNull(),readAt:integer('read_at')},t=>[index('idx_reader_messages_recipient_created').on(t.recipient,t.created)]);
export const adjustments=sqliteTable('point_adjustments',{id:text('id').primaryKey(),recipient:text('recipient').notNull(),amount:integer('amount').notNull(),reason:text('reason').notNull(),created:integer('created').notNull(),applied:integer('applied').notNull().default(0)},t=>[index('idx_point_adjustments_recipient_created').on(t.recipient,t.created)]);
export const customBooks=sqliteTable('custom_books',{id:text('id').primaryKey(),data:text('data').notNull(),published:integer('published').notNull().default(0),created:integer('created').notNull(),updated:integer('updated').notNull()},t=>[index('idx_custom_books_published_created').on(t.published,t.created)]);

export const admins=sqliteTable('library_admins',{userId:text('user_id').primaryKey(),grantedBy:text('granted_by').notNull(),created:integer('created').notNull()});
export const blockedBooks=sqliteTable('reader_book_blocks',{userId:text('user_id').notNull(),book:text('book').notNull(),created:integer('created').notNull(),createdBy:text('created_by').notNull()},t=>[primaryKey({columns:[t.userId,t.book]})]);
export const warningReceipts=sqliteTable('warning_receipts',{id:text('id').primaryKey(),recipient:text('recipient').notNull(),fingerprint:text('fingerprint').notNull(),warningCount:integer('warning_count').notNull(),deleted:integer('deleted').notNull(),applied:integer('applied').notNull().default(0),created:integer('created').notNull()});
export const removals=sqliteTable('profile_removals',{userId:text('user_id').primaryKey(),created:integer('created').notNull()});
